from datetime import date

"""
Career Interpretive Insights

Pre-computes structural career patterns from raw aggregator data and returns
labeled facts for LLM injection. Eliminates the need for the LLM to re-derive
career signals from raw pillars under token constraints.

Output structure:
    {
        "命盘职业格局": [...],   # natal structural facts — always true
        "大运职业动态": [...],   # temporal layer — only cycles with career effects
        "无格局提示":   str|None
    }

Natal patterns are organised in five tiers:
  Tier 1 — Career foundation (官星/印星 strength, visibility)
  Tier 1b — Career star sub-types (正官 vs 七杀)
  Tier 2 — Career style (食伤/比劫/财星/官印synergy)
  Tier 3 — Pillar-specific patterns (family/midlife/self-employed/late)
  Tier 4 — Career interaction patterns (clash/harm/combination)
  Tier 5 — 神煞 patterns (leaders, fierce, noble, academic, salary, travel)

Cycle events are produced by eight focused helpers called from _get_cycle_career_events.

Usage:
    from src.astronomer_calculations.interpretive_insights_career import extract_career_insights
    career_insights = extract_career_insights(raw_data)
"""

# ── Constants ──────────────────────────────────────────────────────────────────

CAREER_STARS = {"正官", "七杀"}
OFFICIAL_STAR = {"正官"}
KILLER_STAR = {"七杀"}
YIN_STARS = {"正印", "偏印"}
FOOD_GOD_HURT_OFFICER = {"食神", "伤官"}
PEER_STARS = {"比肩", "劫财"}
WEALTH_STARS = {"正财", "偏财"}
PILLARS = ["年柱", "月柱", "日柱", "时柱"]
BRANCH_TIERS = ["本气", "中气", "余气"]
ACTIVE_STRENGTHS = {"强势主流", "显著影响", "中等影响"}

# Five-element generation cycle: 木 → 火 → 土 → 金 → 水 → 木
# 印星 element = element that generates Day Master element (one step back)
YIN_ELEMENT_MAP = {"木": "水", "火": "木", "土": "火", "金": "土", "水": "金"}
# 食伤 element = element generated by Day Master element (one step ahead)
FOOD_GOD_HURT_OFFICER_ELEMENT_MAP = {
    "木": "火",
    "火": "土",
    "土": "金",
    "金": "水",
    "水": "木",
}
# 财星 element = element controlled by Day Master (opposite of generation cycle)
WEALTH_ELEMENT_MAP = {"木": "土", "火": "金", "土": "水", "金": "木", "水": "火"}

# Strength thresholds for pattern detection
STRONG_ENOUGH = {"中和", "偏旺", "极旺", "极亢"}
WEAK_ENOUGH = {"偏弱", "极弱"}

# Maps branch label → pillar name for interactions lookup
BRANCH_LABEL_TO_PILLAR = {
    "年支": "年柱",
    "月支": "月柱",
    "日支": "日柱",
    "时支": "时柱",
}

# Heavenly stem to element mapping
STEM_ELEMENT_MAP = {
    "甲": "木",
    "乙": "木",
    "丙": "火",
    "丁": "火",
    "戊": "土",
    "己": "土",
    "庚": "金",
    "辛": "金",
    "壬": "水",
    "癸": "水",
}

# Earthly branch to primary element mapping
BRANCH_ELEMENT_MAP = {
    "子": "水",
    "丑": "土",
    "寅": "木",
    "卯": "木",
    "辰": "土",
    "巳": "火",
    "午": "火",
    "未": "土",
    "申": "金",
    "酉": "金",
    "戌": "土",
    "亥": "水",
}

# Synthesis taxonomy — classify fired patterns by structural role
PRIMARY_PATTERNS = {
    "midlife_career_peak",  # 月令仕途旺 — strongest anchor
    "expression_career",  # 食伤主职 — creative/entrepreneurial anchor
    "career_combined_with_dm",  # 日主合官 — calling/identity anchor
}
SUPPLEMENTARY_IDS = {
    "career_star_visible",
    "career_star_hidden",
    "career_star_strong",
    "seal_support_present",
    "official_career",
    "killer_career",
    "officer_seal_chain",
    "family_career",
    "self_employed",
    "day_pillar_career",
    "late_career_success",
    "wealth_from_career",
    "peer_career",
    "expression_controls_killer",
    "noble_support",
    "leader_star_present",
    "fierce_leader",
    "salary_star",
    "academic_star",
    "travel_career",
    "month_pillar_career_harmonious",
    "career_activated_now",
}
RISK_IDS = {
    "career_star_weak",
    "no_career_star",
    "career_void",
    "career_clashed",
    "career_harmed",
    "career_punished",
    "seal_support_weak",
    "month_pillar_career_clashed",
}

# ── Synthesis template matrix ──────────────────────────────────────────────────
_SYNTH: dict[str | None, dict[tuple, str]] = {
    "月令仕途旺": {
        (False, False): "月令官星稳固，职业轨道清晰，中年事业最为突出。",
        (True, False): "月令官星稳固，{supp_str}为辅，职业路径清晰而有支撑。",
        (False, True): "月令官星稳固，但{risk_str}需留意，职业推进中有阻力。",
        (True, True): "月令官星稳固，{supp_str}为辅，{risk_str}需留意管理。",
    },
    "食伤主职": {
        (False, False): "命盘食伤主导，天赋在创意与表达，职业走独立或创业路线。",
        (True, False): "食伤为职业主轴，{supp_str}加持，创业或创意路径获得支撑。",
        (False, True): "食伤旺盛主职，{risk_str}影响稳定性，需在自由与结构间寻得平衡。",
        (True, True): "食伤主职，{supp_str}辅助，{risk_str}影响需留意。",
    },
    "日主合官": {
        (
            False,
            False,
        ): "日主与官星互合，职业即自我表达，工作是个人认同的延伸，事业与命格一体。",
        (
            True,
            False,
        ): "日主与官星互合，{supp_str}强化基础，职业路径与自我完全融合，事业清晰而有力。",
        (
            False,
            True,
        ): "日主与官星互合，{risk_str}形成内部张力，自我表达与外部压力并存，需在冲突中寻得平衡。",
        (
            True,
            True,
        ): "日主与官星互合，{supp_str}提供支撑，但{risk_str}带来挑战，事业即自我，需在矛盾中前行。",
    },
    None: {  # No primary anchor
        (False, False): "命盘职业格局不显著，事业走向主要依赖大运与自身努力。",
        (True, False): "无明显主格局；辅助因素（{supp_str}）有所助益。",
        (False, True): "无明显主格局；风险因素（{risk_str}）需留意管理。",
        (
            True,
            True,
        ): "无明显主格局；辅助因素（{supp_str}）有所助益，风险因素（{risk_str}）需留意管理。",
    },
}
# Fallback templates for any future primary patterns
_SYNTH_DEFAULT: dict[tuple, str] = {
    (
        True,
        False,
    ): "{anchor_name}格局确立；{supp_str}进一步强化职业基础，整体格局扎实。",
    (False, True): "{anchor_name}格局确立；但{risk_str}需留意，职业发挥可能受到制约。",
    (
        True,
        True,
    ): "{anchor_name}格局确立；{supp_str}提供助力，同时{risk_str}带来挑战，整体职业正面但需主动管理。",
    (False, False): "{anchor_name}格局确立，职业结构有利，依托命盘固有优势稳步发展。",
}


# ── Shared helpers ─────────────────────────────────────────────────────────────


def _get_career_star_positions(shi_shen: dict, bazi: dict) -> dict:
    """
    Scans shi_shen["十神"] for 正官/七杀 appearances across all four pillars.
    Also captures the element of each career star from the pillar's stem or branch.
    Returns:
      {
        "in_stems":      ["年干", ...],
        "in_branches":   ["年支本气", ...],
        "all":           [...combined...],
        "official":      [...official positions...],
        "killer":        [...killer positions...],
        "elements":      {"年干": "木", ...}  # element for each position
      }
    """
    in_stems, in_branches = [], []
    official_pos, killer_pos = [], []
    elements = {}
    ba_zi = bazi.get("八字", {})

    for pillar in PILLARS:
        p = shi_shen.get(pillar, {})
        pillar_bazi = ba_zi.get(pillar, {})
        stem = pillar_bazi.get("天干")
        branch = pillar_bazi.get("地支")

        stem_god = p.get("天干十神")
        if stem_god in CAREER_STARS:
            stem_label = pillar[:1] + "干"
            in_stems.append(stem_label)
            if stem in STEM_ELEMENT_MAP:
                elements[stem_label] = STEM_ELEMENT_MAP[stem]
            if stem_god == "正官":
                official_pos.append(stem_label)
            else:
                killer_pos.append(stem_label)

        for tier in BRANCH_TIERS:
            branch_god = p.get("地支十神", {}).get(tier)
            if branch_god in CAREER_STARS:
                branch_label = pillar[:1] + "支" + tier
                in_branches.append(branch_label)
                # For branch positions, use the branch's element
                if branch in BRANCH_ELEMENT_MAP:
                    elements[branch_label] = BRANCH_ELEMENT_MAP[branch]
                if branch_god == "正官":
                    official_pos.append(branch_label)
                else:
                    killer_pos.append(branch_label)

    return {
        "in_stems": in_stems,
        "in_branches": in_branches,
        "all": in_stems + in_branches,
        "official": official_pos,
        "killer": killer_pos,
        "elements": elements,
    }


def _get_star_positions_by_type(
    shi_shen: dict, star_set: set, sub_type_map: dict[str, str]
) -> dict:
    """
    Generic scanner for ten-god positions. Reduces code duplication across scanners.

    Args:
        shi_shen: The 十神 data structure
        star_set: Set of ten-god types to scan for (e.g., YIN_STARS)
        sub_type_map: Mapping from ten-god to sub-category key (e.g., {"正印": "zheng_yin", "偏印": "pian_yin"})

    Returns dict with keys: in_stems, in_branches, all, plus sub-category keys
    """
    in_stems, in_branches = [], []
    subs = {key: [] for key in set(sub_type_map.values())}

    for pillar in PILLARS:
        p = shi_shen.get(pillar, {})
        stem_god = p.get("天干十神")
        if stem_god in star_set:
            stem_label = pillar[:1] + "干"
            in_stems.append(stem_label)
            if stem_god in sub_type_map:
                subs[sub_type_map[stem_god]].append(stem_label)

        for tier in BRANCH_TIERS:
            branch_god = p.get("地支十神", {}).get(tier)
            if branch_god in star_set:
                branch_label = pillar[:1] + "支" + tier
                in_branches.append(branch_label)
                if branch_god in sub_type_map:
                    subs[sub_type_map[branch_god]].append(branch_label)

    return {
        "in_stems": in_stems,
        "in_branches": in_branches,
        "all": in_stems + in_branches,
        **subs,
    }


def _get_yin_stars_positions(shi_shen: dict) -> dict:
    """Scans for 正印/偏印 appearances."""
    return _get_star_positions_by_type(
        shi_shen,
        YIN_STARS,
        {"正印": "zheng_yin", "偏印": "pian_yin"},
    )


def _get_food_god_hurt_officer_positions(shi_shen: dict) -> dict:
    """Scans for 食神/伤官."""
    return _get_star_positions_by_type(
        shi_shen,
        FOOD_GOD_HURT_OFFICER,
        {"食神": "food", "伤官": "hurt"},
    )


def _get_peer_stars_positions(shi_shen: dict) -> dict:
    """Scans for 比肩/劫财."""
    return _get_star_positions_by_type(
        shi_shen,
        PEER_STARS,
        {"比肩": "bi_jie", "劫财": "jie"},
    )


def _get_branch_chars(bazi: dict) -> dict:
    """Returns {"年支": "丑", "月支": "亥", "日支": "辰", "时支": "申"}"""
    ba_zi = bazi["八字"]
    return {
        "年支": ba_zi["年柱"]["地支"],
        "月支": ba_zi["月柱"]["地支"],
        "日支": ba_zi["日柱"]["地支"],
        "时支": ba_zi["时柱"]["地支"],
    }


def _void_branch_positions(branch_chars: dict, xun_kong: dict) -> set:
    """
    Returns set of branch position keys where that pillar's branch falls in 旬空.
    """
    voided = set()
    for branch_key, branch_char in branch_chars.items():
        pillar_key = branch_key[:1] + "柱"
        xun_kong_str = xun_kong.get("旬空", {}).get(pillar_key, {}).get("旬空", "")
        if branch_char in xun_kong_str:
            voided.add(branch_key)
    return voided


def _has_chong_xing_on_pillar(pillar_name: str, interactions: dict) -> bool:
    """Return True if pillar has active 六冲 or 三刑.

    Args:
        pillar_name: Name of pillar (e.g., "月柱")
        interactions: Either full interactions dict with "作用" key, or just the "作用" dict
    """
    # Handle both full interactions dict and extracted "作用" dict
    if "柱位动态" in interactions:
        # Already extracted "作用" dict
        pillar_data = interactions.get("柱位动态", {}).get(pillar_name, {})
    else:
        # Full interactions dict
        pillar_data = (
            interactions.get("作用", {}).get("柱位动态", {}).get(pillar_name, {})
        )
    for tier_items in pillar_data.values():
        if not isinstance(tier_items, list):
            continue
        for item in tier_items:
            if item.get("类型") in {"六冲", "无恩之刑", "恃势之刑", "无礼之刑", "自刑"}:
                if item.get("强度") in ACTIVE_STRENGTHS:
                    return True
    return False


def _get_current_decade(da_yun: dict) -> dict | None:
    """Return the decade dict with 当运 == True, or None if not found."""
    cycles = da_yun.get("大运", {}).get("大运周期", [])
    for cycle in cycles[1:]:
        if cycle.get("当运"):
            return cycle
    return None


def _decade_has_career(decade: dict) -> bool:
    """True if the decade's 运柱 contains 官杀 or significant ten-god impact."""
    run_zhu = decade.get("运柱", {})
    if not isinstance(run_zhu, dict):
        return False
    shi_shen = run_zhu.get("十神", {})
    if shi_shen.get("天干", {}).get("十神") in CAREER_STARS:
        return True
    for tier in BRANCH_TIERS:
        tier_data = shi_shen.get(tier)
        if isinstance(tier_data, dict) and tier_data.get("十神") in CAREER_STARS:
            return True
    return False


# ── Natal pattern functions ───────────────────────────────────────────────────


# ── Tier 1: Career Foundation ──────────────────────────────────────────────────


def _pattern_career_star_visible(csp: dict) -> dict | None:
    if not (len(csp["in_stems"]) > 0):
        return None
    return {
        "解读": "官星透出天干，职业野心与事业抱负外显，追求明确。",
        "依据": f"官星透干: {csp['in_stems']}",
    }


def _pattern_career_star_hidden(csp: dict) -> dict | None:
    if not (len(csp["in_stems"]) == 0 and len(csp["in_branches"]) > 0):
        return None
    return {
        "解读": "官星藏于地支，职业心志深沉内敛，内在责任感强而不事张扬。",
        "依据": f"官星藏支: {csp['in_branches']}；天干无官星",
    }


def _pattern_career_star_strong(wu_xing: dict, csp: dict, dm_score: int) -> dict | None:
    if not csp["all"]:
        return None
    # Check if ANY career star element is strong (multiple 官杀 possible with different elements)
    strong_elements = []
    for pos in csp["in_stems"] + csp["in_branches"]:
        if pos not in csp["elements"]:
            continue
        career_element = csp["elements"][pos]
        career_strength = wu_xing.get("五行力量分析", {}).get(career_element, {})
        if career_strength and career_strength.get("旺衰") in STRONG_ENOUGH:
            strong_elements.append(career_element)

    if not strong_elements:
        return None
    # Remove duplicates while preserving first-seen order for stable output
    unique_elements = list(dict.fromkeys(strong_elements))
    element_str = (
        "、".join(unique_elements) if len(unique_elements) > 1 else unique_elements[0]
    )
    strength_str = (
        wu_xing.get("五行力量分析", {}).get(unique_elements[0], {}).get("旺衰", "")
    )

    # Nuance based on constitutional strength
    if dm_score >= 3:
        interpretation = "官星旺盛，职业驱动力强，天生有领导气质与事业心，体质强健能充分发挥，易居管理或决策位置。"
    elif dm_score <= 1:
        interpretation = "官星旺盛有心志，但体质脆弱难以充分发挥，职业心志受制于精力与健康，需在保持体质基础上稳步推进。"
    else:  # dm_score == 2
        interpretation = (
            "官星旺盛，职业驱动力强，天生有领导气质与事业心，易居管理或决策位置。"
        )

    return {
        "解读": interpretation,
        "依据": f"官星元素{element_str}旺度: {strength_str}；日主强弱分数: {dm_score}/5",
    }


def _pattern_career_star_weak(wu_xing: dict, csp: dict, dm_score: int) -> dict | None:
    if not csp["all"]:
        return None
    # Check if ALL career star elements are weak (multiple 官杀 possible with different elements)
    weak_elements = []
    for pos in csp["in_stems"] + csp["in_branches"]:
        if pos not in csp["elements"]:
            continue
        career_element = csp["elements"][pos]
        career_strength = wu_xing.get("五行力量分析", {}).get(career_element, {})
        if career_strength and career_strength.get("旺衰") in WEAK_ENOUGH:
            weak_elements.append(career_element)

    # Only fire pattern if ALL career stars are weak (not just one)
    if len(weak_elements) != len(
        [p for p in csp["in_stems"] + csp["in_branches"] if p in csp["elements"]]
    ):
        return None

    # Remove duplicates while preserving first-seen order for stable output
    unique_elements = list(dict.fromkeys(weak_elements))
    element_str = (
        "、".join(unique_elements) if len(unique_elements) > 1 else unique_elements[0]
    )
    strength_str = (
        wu_xing.get("五行力量分析", {}).get(unique_elements[0], {}).get("旺衰", "")
    )

    # Nuance based on constitutional strength
    if dm_score >= 3:
        interpretation = "官星微弱，职业心志虽有，但因体质强健，可通过自身努力与持续行动补偿，适合独立创业或自我管理，抗拒权威而能自驱。"
    elif dm_score <= 1:
        interpretation = "官星微弱，职业心志无力推动，体质脆弱更难推进事业，需要外在支持或选择稳定位置，自我管理与创业风险较高。"
    else:  # dm_score == 2
        interpretation = "官星微弱，职业心志虽有但无力推动，更适合独立创业或自我管理，抗拒外界权威压制。"

    return {
        "解读": interpretation,
        "依据": f"官星元素{element_str}旺度: {strength_str}；日主强弱分数: {dm_score}/5",
    }


def _pattern_no_career_star(
    csp: dict, food_pos: dict, wealth_pos: dict, wu_xing: dict, dm_element: str
) -> dict | None:
    if csp["all"]:
        return None
    # Check if 食伤 is strong (its element is generated by DM element)
    food_element = FOOD_GOD_HURT_OFFICER_ELEMENT_MAP.get(dm_element)
    food_strength = (
        wu_xing.get("五行力量分析", {}).get(food_element, {}) if food_element else {}
    )
    food_strong = food_pos["all"] and food_strength.get("旺衰") in STRONG_ENOUGH

    # Check if 财星 is strong (its element is controlled by DM element)
    wealth_element = WEALTH_ELEMENT_MAP.get(dm_element)
    wealth_strength = (
        wu_xing.get("五行力量分析", {}).get(wealth_element, {})
        if wealth_element
        else {}
    )
    wealth_strong = wealth_pos["all"] and wealth_strength.get("旺衰") in STRONG_ENOUGH

    if food_strong or wealth_strong:
        return {
            "解读": "无官无杀，职业走自主或创意路线；食伤/财星旺盛，可依靠才能或商业驱动事业。",
            "依据": "无官杀；食伤或财星为职业替代动力",
        }
    return {
        "解读": "无官无杀，职业不为人生核心关注，可能倾向稳定工作或人生其他领域优先。",
        "依据": "无官杀；无显著替代职业星",
    }


def _pattern_seal_support_present(
    yin_pos: dict, wu_xing: dict, dm_element: str
) -> dict | None:
    if not yin_pos["all"]:
        return None
    # 印星 element is the element that generates DM element (one step back in cycle)
    yin_element = YIN_ELEMENT_MAP.get(dm_element)
    if not yin_element:
        return None
    yin_strength = wu_xing.get("五行力量分析", {}).get(yin_element, {})
    if yin_strength.get("旺衰") not in STRONG_ENOUGH:
        return None
    return {
        "解读": "印星有力，受教育与导师支撑深厚，职业基础建立在知识与信誉上，机构背景助力。",
        "依据": f"印星位置: {yin_pos['all']}；印星元素{yin_element}旺度: {yin_strength.get('旺衰')}",
    }


def _pattern_seal_support_weak(
    yin_pos: dict, wu_xing: dict, dm_element: str
) -> dict | None:
    yin_element = YIN_ELEMENT_MAP.get(dm_element)
    yin_tier = (
        wu_xing.get("五行力量分析", {}).get(yin_element, {}).get("旺衰", "")
        if yin_element
        else ""
    )

    if not yin_pos["all"]:
        return {
            "解读": "印星不足，缺乏机构支撑与导师助力，职业多为自学与实战驱动，独立自主更强。",
            "依据": "无印星；职业需自我突破与努力驱动",
        }

    if yin_tier in WEAK_ENOUGH:
        return {
            "解读": "印星偏弱，导师与制度支撑存在但承托力有限，职业更依赖自我驱动与持续实践。",
            "依据": f"印星位置: {yin_pos['all']}；印星元素{yin_element}旺度: {yin_tier}",
        }

    return None


# ── Tier 1b: Career Star Sub-types ─────────────────────────────────────────────


def _pattern_official_career(csp: dict, dm_score: int) -> dict | None:
    if not (csp["official"] and not csp["killer"]):
        return None

    # Nuance based on constitutional strength
    if dm_score >= 3:
        interpretation = "正官独占，职业路径结构化、纪律性强，体质强健能充分发挥规范优势，易成为精干的组织干部与决策者。"
    elif dm_score <= 1:
        interpretation = "正官独占，职业路径结构化、纪律性强，但体质脆弱难以应对长期的规范压力与责任负荷，需在制度框架内寻得均衡。"
    else:  # dm_score == 2
        interpretation = (
            "正官独占，职业路径结构化、纪律性强，喜欢在制度框架内发展，易成为组织干部。"
        )

    return {
        "解读": interpretation,
        "依据": f"仅正官位置: {csp['official']}；日主强弱分数: {dm_score}/5",
    }


def _pattern_killer_career(csp: dict, dm_score: int) -> dict | None:
    if not (csp["killer"] and not csp["official"]):
        return None

    # Nuance based on constitutional strength
    if dm_score >= 3:
        interpretation = "七杀主导，职业竞争性强、高压驱动，体质强健能驾驭高压环境，擅长在激烈竞争中突破，企业家或破局者特质。"
    elif dm_score <= 1:
        interpretation = "七杀主导，职业竞争性强、高压驱动，但体质脆弱难以长期承受高压与竞争，需要选择相对稳定环境或学会压力管理，否则易因过度消耗而倒下。"
    else:  # dm_score == 2
        interpretation = "七杀主导，职业竞争性强、高压驱动，擅长在激烈环境中突破，企业家或破局者特质。"

    return {
        "解读": interpretation,
        "依据": f"仅七杀位置: {csp['killer']}；日主强弱分数: {dm_score}/5",
    }


# ── Tier 2: Career Style ───────────────────────────────────────────────────────


def _pattern_expression_career(
    food_pos: dict, wu_xing: dict, dm_element: str, dm_score: int
) -> dict | None:
    if not food_pos["all"]:
        return None
    food_element = FOOD_GOD_HURT_OFFICER_ELEMENT_MAP.get(dm_element)
    if not food_element:
        return None
    food_strength = wu_xing.get("五行力量分析", {}).get(food_element, {})
    if food_strength.get("旺衰") not in STRONG_ENOUGH:
        return None

    # Nuance based on constitutional strength
    if dm_score >= 3:
        interpretation = "食伤旺盛，职业走创意、技艺或自由表达路线，体质强健能持续输出，自我管理优于受约束，创业或自由职业契合度高。"
    elif dm_score <= 1:
        interpretation = "食伤旺盛，创意与表达欲强，但体质脆弱难以长期持续输出与自我管理，创业风险较高，需要寻找允许灵活与调整的职业形式。"
    else:  # dm_score == 2
        interpretation = "食伤旺盛，职业走创意、技艺或自由表达路线，自我管理优于受约束，创业或自由职业契合。"

    return {
        "解读": interpretation,
        "依据": f"食伤元素{food_element}旺度: {food_strength.get('旺衰')}；日主强弱分数: {dm_score}/5",
    }


def _pattern_expression_controls_killer(
    food_pos: dict, killer_pos: dict, wu_xing: dict, dm_element: str, dm_score: int
) -> dict | None:
    if not (food_pos["all"] and killer_pos):
        return None
    food_element = FOOD_GOD_HURT_OFFICER_ELEMENT_MAP.get(dm_element)
    if not food_element:
        return None
    food_strength = wu_xing.get("五行力量分析", {}).get(food_element, {})
    if food_strength.get("旺衰") not in STRONG_ENOUGH:
        return None

    # Nuance based on constitutional strength
    if dm_score >= 3:
        interpretation = "食伤制杀，创意与表达制约了竞争压力，体质强健能在高压中保持创造力，职业走创新突破路线，具备企业家精神。"
    elif dm_score <= 1:
        interpretation = "食伤制杀，创意可制约七杀竞争，但体质脆弱，长期高压与创意透支易导致身心俱疲，需要严格的恢复周期与工作节奏管理。"
    else:  # dm_score == 2
        interpretation = "食伤制杀，创意与表达制约了竞争压力，职业走创新突破路线，可在高压中保持创造力。"

    return {
        "解读": interpretation,
        "依据": f"食伤制杀存在；食伤元素强度: {food_strength.get('旺衰')}；日主强弱分数: {dm_score}/5",
    }


def _pattern_peer_career(peer_pos: dict, wu_xing: dict, dm_element: str) -> dict | None:
    if not peer_pos["all"]:
        return None
    peer_element = dm_element
    peer_strength = wu_xing.get("五行力量分析", {}).get(peer_element, {})
    if peer_strength.get("旺衰") not in STRONG_ENOUGH:
        return None
    return {
        "解读": "比劫旺盛，职业走团队合作、竞争并存路线，善于管理平级关系，合伙创业或团队领导力强。",
        "依据": f"比劫元素旺度: {peer_strength.get('旺衰')}",
    }


def _pattern_wealth_from_career(shi_shen: dict) -> dict | None:
    # Check if 财星 appears in Month or Day Pillar
    for pillar in ["月柱", "日柱"]:
        p = shi_shen.get(pillar, {})
        if p.get("天干十神") in WEALTH_STARS:
            return {
                "解读": "财星入职业宫，工作与收入直接挂钩，薪酬与事业发展紧密相关。",
                "依据": f"{pillar}十神为财星",
            }
        for tier in BRANCH_TIERS:
            if p.get("地支十神", {}).get(tier) in WEALTH_STARS:
                return {
                    "解读": "财星入职业宫，工作与收入直接挂钩，薪酬与事业发展紧密相关。",
                    "依据": f"{pillar}支十神为财星",
                }
    return None


def _pattern_career_combined_with_dm(
    interactions: dict, dm_stem: str, csp: dict
) -> dict | None:
    if not csp["in_stems"]:
        return None
    # Check if DM stem combines with any 官星 stem via 天干合
    # Search through 柱位动态 for 天干合 interactions
    pillar_data = interactions.get("作用", {}).get("柱位动态", {})
    career_stem_pillars = {pos[0] + "柱" for pos in csp["in_stems"]}
    career_stem_labels = set(csp["in_stems"])

    for pillar, tier_dict in pillar_data.items():
        # Search through all tiers (第一梯队, 第二梯队, 第三梯队)
        for tier_list in tier_dict.values():
            if not isinstance(tier_list, list):
                continue
            for item in tier_list:
                if item.get("类型") != "天干合":
                    continue
                if item.get("强度") not in ACTIVE_STRENGTHS:
                    continue
                # Check if DM stem and a career star stem are combined
                detail = item.get("组合明细", {})
                stems_in_combo = [v for v in detail.values() if isinstance(v, str)]
                if dm_stem not in stems_in_combo:
                    continue
                detail_keys = set(detail.keys())
                has_career_key = bool(
                    (detail_keys & career_stem_pillars)
                    or (detail_keys & career_stem_labels)
                )
                if has_career_key:
                    return {
                        "解读": "日主与官星相合，职业与自我完全融合，工作即生活，事业是自我表达的载体。",
                        "依据": f"天干合: {dm_stem} 与官星相合；强度: {item.get('强度')}",
                    }
    return None


def _pattern_officer_seal_chain(
    csp: dict, yin_pos: dict, wu_xing: dict, dm_element: str
) -> dict | None:
    if not (csp["all"] and yin_pos["all"]):
        return None

    # Get the actual career star element (from csp which already captured it)
    career_element = None
    for pos in csp["in_stems"] + csp["in_branches"]:
        if pos in csp["elements"]:
            career_element = csp["elements"][pos]
            break

    # Get the actual yin star element
    yin_element = YIN_ELEMENT_MAP.get(dm_element)

    if not career_element or not yin_element:
        return None

    # Verify they're in generation relationship (官星元素 generates 印星元素 in the cycle)
    if FOOD_GOD_HURT_OFFICER_ELEMENT_MAP.get(career_element) != yin_element:
        return None

    # Check strength: at least one must be truly strong, both must not be weak
    career_strength = wu_xing.get("五行力量分析", {}).get(career_element, {})
    yin_strength = wu_xing.get("五行力量分析", {}).get(yin_element, {})

    career_tier = career_strength.get("旺衰", "")
    yin_tier = yin_strength.get("旺衰", "")

    # Pattern fires if: generation relationship exists AND at least one is strong (偏旺+) AND both avoid extreme weakness
    truly_strong = {"偏旺", "极旺", "极亢"}
    not_weak = {"中和", "偏旺", "极旺", "极亢"}

    has_truly_strong = (career_tier in truly_strong) or (yin_tier in truly_strong)
    both_acceptable = (career_tier in not_weak) and (yin_tier in not_weak)

    if has_truly_strong and both_acceptable:
        return {
            "解读": "官印相生，权力与知识并行，职业路径兼具权威与信誉，学而优则仕的典型。",
            "依据": f"官星元素{career_element}生印星元素{yin_element}; 官星旺度: {career_tier}; 印星旺度: {yin_tier}",
        }
    return None


# ── Tier 3: Pillar-Specific ────────────────────────────────────────────────────


def _pattern_family_career(shi_shen: dict) -> dict | None:
    p = shi_shen.get("年柱", {})
    stem_god = p.get("天干十神")
    if stem_god in CAREER_STARS | YIN_STARS:
        return {
            "解读": "祖业职业格，职业方向由家族设定或家族背景助力，继承或突破父业，早年方向已定。",
            "依据": f"年柱十神: {stem_god}",
        }
    for tier in BRANCH_TIERS:
        branch_god = p.get("地支十神", {}).get(tier)
        if branch_god in CAREER_STARS | YIN_STARS:
            return {
                "解读": "祖业职业格，职业方向由家族设定或家族背景助力，继承或突破父业，早年方向已定。",
                "依据": f"年柱支十神: {branch_god}",
            }
    return None


def _pattern_midlife_career_peak(
    shi_shen: dict, wu_xing: dict, dm_element: str, csp: dict, dm_score: int
) -> dict | None:
    # Check if month pillar has any career star (stem or branch)
    if not any(pos.startswith("月") for pos in csp["all"]):
        return None

    # Get the element of the career star from csp
    career_element = None
    # Check stem first
    for pos in csp["in_stems"]:
        if pos.startswith("月") and pos in csp["elements"]:
            career_element = csp["elements"][pos]
            break
    # If not in stem, check branch
    if not career_element:
        for pos in csp["in_branches"]:
            if pos.startswith("月") and pos in csp["elements"]:
                career_element = csp["elements"][pos]
                break

    if not career_element:
        return None

    career_strength = wu_xing.get("五行力量分析", {}).get(career_element, {})
    if career_strength.get("旺衰") in STRONG_ENOUGH:
        # Nuance based on constitutional strength
        if dm_score >= 3:
            interpretation = "月令官星格局，职业核心在中年30-50岁，体质强健能充分发挥此阶段优势，事业最为突出、成就最显著，中年事业高峰强有力。"
        elif dm_score <= 1:
            interpretation = "月令官星格局，职业核心在中年30-50岁，但体质脆弱可能因健康或精力限制而难以充分把握此窗口，需在健康保证下稳步推进。"
        else:  # dm_score == 2
            interpretation = "月令官星格局，职业核心在中年30-50岁，此阶段事业最为突出、成就最显著，中年事业高峰。"

        return {
            "解读": interpretation,
            "依据": f"月柱官星；官星元素{career_element}旺度: {career_strength.get('旺衰')}；日主强弱分数: {dm_score}/5",
        }
    return None


def _pattern_self_employed(shi_shen: dict) -> dict | None:
    day_god = shi_shen.get("日柱", {}).get("天干十神")
    month_god = shi_shen.get("月柱", {}).get("天干十神")

    # Check if career star is hidden in month branch
    month_branch_has_career = False
    month_branch_shi_shen = shi_shen.get("月柱", {}).get("地支十神", {})
    for tier in BRANCH_TIERS:
        if month_branch_shi_shen.get(tier) in CAREER_STARS:
            month_branch_has_career = True
            break

    # Pattern fires: day has wealth, month has no career stars (stem or branch)
    if (
        day_god in WEALTH_STARS
        and month_god not in CAREER_STARS
        and not month_branch_has_career
    ):
        return {
            "解读": "自主创业格，日柱有财而月柱无官，职业走自我管理、自主经营路线，独立创业或自由职业。",
            "依据": f"日柱十神为财星；月柱十神无官杀（包括隐藏官杀）",
        }
    return None


def _pattern_day_pillar_career(shi_shen: dict) -> dict | None:
    """
    Detects when day pillar contains a career star (官杀).
    Signals personal work identity, self-employment capability, strong personal work style.
    """
    day_god = shi_shen.get("日柱", {}).get("天干十神")
    if day_god in CAREER_STARS:
        return {
            "解读": "日主合官，职业即自我，工作是个人身份认同的核心，自主性强、自主创业或专业精专，工作生活难分开，对职业的投入程度深。",
            "依据": f"日柱十神: {day_god}",
        }

    # Check day branch for hidden career star
    day_branch_shi_shen = shi_shen.get("日柱", {}).get("地支十神", {})
    for tier in BRANCH_TIERS:
        branch_god = day_branch_shi_shen.get(tier)
        if branch_god in CAREER_STARS:
            return {
                "解读": "日坐官星，职业与个人身份深度绑定。工作不仅是谋生手段，更是自我价值的核心表达。适合独立执业、自由职业或家庭事业，职业生涯与生活节奏高度融合。",
                "依据": f"日柱支十神: {branch_god}",
            }
    return None


def _pattern_late_career_success(shi_shen: dict) -> dict | None:
    p = shi_shen.get("时柱", {})
    stem_god = p.get("天干十神")
    if stem_god in CAREER_STARS | WEALTH_STARS:
        return {
            "解读": "晚年仕途格，职业成就、事业巅峰、商业成功在50岁后，人生下半场事业最为辉煌。",
            "依据": f"时柱十神: {stem_god}",
        }
    for tier in BRANCH_TIERS:
        branch_god = p.get("地支十神", {}).get(tier)
        if branch_god in CAREER_STARS | WEALTH_STARS:
            return {
                "解读": "晚年仕途格，职业成就、事业巅峰、商业成功在50岁后，人生下半场事业最为辉煌。",
                "依据": f"时柱支十神: {branch_god}",
            }
    return None


def _pattern_career_void(csp: dict, voided_branches: set) -> dict | None:
    if not csp["all"]:
        return None
    for pos in csp["in_branches"]:
        branch_key = pos[:2]
        if branch_key in voided_branches:
            return {
                "解读": "官星落空，职业成就感容易缺失，机会虽多但易化为虚，事业需主动把握方能成形。",
                "依据": f"官星位置{pos}落旬空",
            }
    return None


# ── Tier 4: Career Interaction ─────────────────────────────────────────────────


def _pattern_career_clashed(
    csp: dict, interactions: dict, branch_chars: dict, dm_score: int
) -> dict | None:
    if not csp["all"]:
        return None
    for pillar in PILLARS:
        if any(pos.startswith(pillar[:1]) for pos in csp["all"]):
            if _has_chong_xing_on_pillar(pillar, interactions):
                # Nuance based on constitutional strength
                if dm_score >= 3:
                    interpretation = "官星受冲，职业路上阻力多、变动频繁，易有跳槽或权力冲突，但因体质强健，能在变动中迅速调整与反弹。"
                elif dm_score <= 1:
                    interpretation = "官星受冲，职业路上阻力多、变动频繁，易有跳槽或权力冲突，体质脆弱更难适应频繁变动，需主动稳定心态与健康基础。"
                else:  # dm_score == 2
                    interpretation = "官星受冲，职业路上阻力多、变动频繁，易有跳槽、调职或权力冲突，需在变动中坚守。"

                return {
                    "解读": interpretation,
                    "依据": f"官星所在{pillar}受冲击；日主强弱分数: {dm_score}/5",
                }
    return None


def _pattern_career_harmed(csp: dict, interactions: dict, dm_score: int) -> dict | None:
    # Check for 六害 only on pillars containing career stars
    if not csp["all"]:
        return None

    # Extract pillar names that contain career stars
    career_pillars = {pos[0] for pos in csp["all"]}  # Extract first char (年/月/日/时)
    pillar_map = {"年": "年柱", "月": "月柱", "日": "日柱", "时": "时柱"}
    career_pillars = {pillar_map[char] for char in career_pillars if char in pillar_map}

    pillar_data = interactions.get("作用", {}).get("柱位动态", {})
    for pillar in career_pillars:
        tier_dict = pillar_data.get(pillar, {})
        for tier_list in tier_dict.values():
            if not isinstance(tier_list, list):
                continue
            for item in tier_list:
                if item.get("类型") == "六害" and item.get("强度") in ACTIVE_STRENGTHS:
                    # Nuance based on constitutional strength
                    if dm_score >= 3:
                        interpretation = "官星受害，职场人际隐患多、同事掣肘隐形，但因体质强健，能较好察觉与应对，需防小人但不必过度忧虑。"
                    elif dm_score <= 1:
                        interpretation = "官星受害，职场人际隐患多、同事掣肘隐形，体质脆弱更易因职场压力与不公正待遇而身心俱疲，需主动识人、谨言慎行、积极防范。"
                    else:  # dm_score == 2
                        interpretation = "官星受害，职场人际隐患多、同事掣肘隐形，需防小人、谨言慎行，不在暗处吃亏。"

                    return {
                        "解读": interpretation,
                        "依据": f"官星所在{pillar}受六害；日主强弱分数: {dm_score}/5",
                    }
    return None


def _pattern_career_punished(
    csp: dict, interactions: dict, dm_score: int
) -> dict | None:
    # Check for 三刑 only on pillars containing career stars
    SAN_XING_TYPES = {"无恩之刑", "恃势之刑", "无礼之刑", "自刑"}
    if not csp["all"]:
        return None

    # Extract pillar names that contain career stars
    career_pillars = {pos[0] for pos in csp["all"]}  # Extract first char (年/月/日/时)
    pillar_map = {"年": "年柱", "月": "月柱", "日": "日柱", "时": "时柱"}
    career_pillars = {pillar_map[char] for char in career_pillars if char in pillar_map}

    pillar_data = interactions.get("作用", {}).get("柱位动态", {})
    for pillar in career_pillars:
        tier_dict = pillar_data.get(pillar, {})
        for tier_list in tier_dict.values():
            if not isinstance(tier_list, list):
                continue
            for item in tier_list:
                if (
                    item.get("类型") in SAN_XING_TYPES
                    and item.get("强度") in ACTIVE_STRENGTHS
                ):
                    # Nuance based on constitutional strength
                    if dm_score >= 3:
                        interpretation = "官星受刑，职场易有结构性冲突、制度性摩擦或规则变动带来的压力，需加强合规意识与流程管理。因体质强健，通常能较快调适并稳住节奏。"
                    elif dm_score <= 1:
                        interpretation = "官星受刑，职场易有结构性冲突、制度性摩擦或规则变动带来的压力，需加强合规意识与流程管理。体质偏弱时压力感更重，宜提前建立支持与缓冲机制。"
                    else:  # dm_score == 2
                        interpretation = "官星受刑，职场易有结构性冲突、制度性摩擦或规则变动带来的压力，需加强合规意识与流程管理。"

                    return {
                        "解读": interpretation,
                        "依据": f"官星所在{pillar}受三刑；日主强弱分数: {dm_score}/5",
                    }
    return None


def _pattern_month_pillar_career_clashed(interactions: dict) -> dict | None:
    if _has_chong_xing_on_pillar("月柱", interactions):
        return {
            "解读": "月柱职业宫受冲，工作状态不稳、环境易变，需在波动中保持定力，大运助力时方能突破。",
            "依据": "月柱受冲击",
        }
    return None


def _pattern_month_pillar_career_harmonious(interactions: dict) -> dict | None:
    pillar_data = interactions.get("作用", {}).get("柱位动态", {}).get("月柱", {})
    for tier_items in pillar_data.values():
        if not isinstance(tier_items, list):
            continue
        for item in tier_items:
            if item.get("类型") in {"六合", "三合", "三会"}:
                if item.get("强度") in ACTIVE_STRENGTHS:
                    return {
                        "解读": "月柱职业宫和谐，工作环境支持、人脉助力，职业推进顺利，事业主轴稳健。",
                        "依据": f"月柱受{item.get('类型')}",
                    }
    return None


def _pattern_career_activated_now(
    current_decade: dict | None, csp: dict
) -> dict | None:
    if not current_decade:
        return None
    run_zhu = current_decade.get("运柱", {})
    if not isinstance(run_zhu, dict):
        return None
    shi_shen = run_zhu.get("十神", {})

    # Check if cycle stem's ten-god is a career star
    stem_god = shi_shen.get("天干", {}).get("十神")
    if stem_god in CAREER_STARS:
        return {
            "解读": "当运事业星激活，目前大运正推动职业机会，是事业突破或晋升的窗口期，主动进取则事半功倍。",
            "依据": f"当前大运十神含官星",
        }

    # Check if cycle carries 将星 神煞
    cycle_shen_sha = current_decade.get("神煞", {})
    cycle_has_leader_star = False
    if isinstance(cycle_shen_sha, dict):
        for shen_list in cycle_shen_sha.values():
            if "将星" in shen_list:
                cycle_has_leader_star = True
                break
    if cycle_has_leader_star:
        return {
            "解读": "当运事业星激活，目前大运正推动职业机会，是事业突破或晋升的窗口期，主动进取则事半功倍。",
            "依据": f"当前大运神煞含将星",
        }
    return None


# ── Tier 5: 神煞 Patterns ──────────────────────────────────────────────────────


def _pattern_leader_star_present(shen_sha: dict) -> dict | None:
    for pillar_shen in shen_sha.values():
        if "将星" in pillar_shen.get("神煞", []):
            return {
                "解读": "将星入命，天生领导气质，易被信任、易成领导者，统御能力强、组织力出众。",
                "依据": "将星现于命盘",
            }
    return None


def _pattern_fierce_leader(shen_sha: dict) -> dict | None:
    for pillar in ["月柱", "日柱"]:
        if "魁罡" in shen_sha.get(pillar, {}).get("神煞", []):
            return {
                "解读": "魁罡主职，性格凶悍、职业竞争性极强，高成就者但易树敌，魄力十足但需修养人脉。",
                "依据": f"{pillar}有魁罡",
            }
    return None


def _pattern_noble_support(shen_sha: dict) -> dict | None:
    for pillar in ["月柱", "日柱"]:
        if "天乙贵人" in shen_sha.get(pillar, {}).get("神煞", []):
            return {
                "解读": "天乙贵人助仕，贵人扶持、机遇自来，职业多获助力，上司提携或机构推荐，事半功倍。",
                "依据": f"{pillar}有天乙贵人",
            }
    return None


def _pattern_academic_star(shen_sha: dict) -> dict | None:
    for pillar in ["月柱", "时柱"]:
        if "文昌" in shen_sha.get(pillar, {}).get("神煞", []):
            return {
                "解读": "文昌主职，才华横溢、笔杆子或知识工作出众，适合教育、写作、研究、顾问等知识型职业。",
                "依据": f"{pillar}有文昌",
            }
    return None


def _pattern_salary_star(shen_sha: dict) -> dict | None:
    for pillar in ["月柱", "日柱"]:
        if "禄神" in shen_sha.get(pillar, {}).get("神煞", []):
            return {
                "解读": "禄神入命，稳定薪酬、编制扶持，适合企业或机关稳定工作，收入保障高、福利齐备。",
                "依据": f"{pillar}有禄神",
            }
    return None


def _pattern_travel_career(shen_sha: dict) -> dict | None:
    for pillar in ["月柱", "时柱"]:
        if "驿马" in shen_sha.get(pillar, {}).get("神煞", []):
            return {
                "解读": "驿马仕途，职业多涉国际或异地，工作需要出差、迁居或跨境，行动力强、适应力佳。",
                "依据": f"{pillar}有驿马",
            }
    return None


# ── Cycle event helpers ────────────────────────────────────────────────────────


def _modulate_career_effect_by_constitution(effect: dict, dm_score: int) -> dict:
    """Modulate cycle career effect 解读 and 强度 based on constitutional strength.

    Args:
        effect: Career effect dict with '解读' and '强度' keys
        dm_score: Day Master strength (0-5)

    Returns:
        Modified effect dict with constitutional context added to 解读 and adjusted 强度
    """
    modified = effect.copy()
    original_jieyue = modified.get("解读", "")

    if dm_score <= 1:
        # Weak constitution: amplify negative impact, downgrade positive opportunity
        strength = modified.get("强度", "")
        effect_type = modified.get("作用类型", "")

        # For disruptive effects, upgrade severity; for opportunities, downgrade
        if (
            "冲" in effect_type
            or "void" in effect_type.lower()
            or "反" in effect_type
            or "伏" in effect_type
        ):
            # Negative effect: amplify
            modified["解读"] = (
                original_jieyue
                + " 因先天体质偏弱，此影响更为显著，职业推进受阻更严重，需格外谨慎与调理。"
            )
            if strength == "中等影响":
                modified["强度"] = "显著影响"
            elif strength == "显著影响":
                modified["强度"] = "强势主流"
        else:
            # Positive effect: downgrade/caution
            modified["解读"] = (
                original_jieyue
                + " 但因体质脆弱，虽有机遇但执行力受限，需健康保障才能真正把握机遇。"
            )
            if strength == "显著影响":
                modified["强度"] = "中等影响"
            elif strength == "中等影响":
                modified["强度"] = "大幅衰减"

    elif dm_score >= 3:
        # Strong constitution: emphasize resilience and opportunity capture
        strength = modified.get("强度", "")
        effect_type = modified.get("作用类型", "")

        # For positive effects, upgrade; for negative, downgrade recovery impact
        if (
            "冲" in effect_type
            or "void" in effect_type.lower()
            or "反" in effect_type
            or "伏" in effect_type
        ):
            # Negative effect: downgrade severity (can recover)
            modified["解读"] = (
                original_jieyue
                + " 因体质强健，能较快调适与反弹，职业压力尚在可控范围。"
            )
            if strength == "强势主流":
                modified["强度"] = "显著影响"
            elif strength == "显著影响":
                modified["强度"] = "中等影响"
        else:
            # Positive effect: emphasize full capture
            modified["解读"] = (
                original_jieyue
                + " 因体质强健，可充分把握机遇，事半功倍，是突破的黄金期。"
            )
            if strength == "中等影响":
                modified["强度"] = "显著影响"
            elif strength == "显著影响":
                modified["强度"] = "强势主流"

    # dm_score == 2 (moderate): no adjustment, use as-is

    return modified


def _cycle_guan_sha_arrives(decade: dict, csp: dict, dm_score: int) -> list:
    """Career activation when cycle brings 官杀"""
    if not _decade_has_career(decade):
        return []
    effect = {
        "作用类型": "事业激活",
        "解读": "大运官星激活，职业机会上升，事业推进有力，突破或晋升在此阶段成形。",
        "互动类型": "官星到位",
        "强度": "中等影响",
    }
    return [_modulate_career_effect_by_constitution(effect, dm_score)]


def _cycle_clashes_career(decade: dict, dm_score: int) -> list:
    """Career disruption when cycle clashes Month Pillar"""
    cycle_interactions = decade.get("作用", {})
    if not cycle_interactions:
        return []
    if _has_chong_xing_on_pillar("月柱", cycle_interactions):
        effect = {
            "作用类型": "事业冲突",
            "解读": "大运冲克月柱，职业环境波动、人脉冲击，工作变动或权力洗牌在此阶段频发。",
            "互动类型": "六冲/三刑",
            "强度": "显著影响",
        }
        return [_modulate_career_effect_by_constitution(effect, dm_score)]
    return []


def _cycle_activates_career(decade: dict, dm_score: int) -> list:
    """Career breakthrough when cycle harmonizes Month Pillar"""
    cycle_interactions = decade.get("作用", {})
    if not cycle_interactions:
        return []
    pillar_data = cycle_interactions.get("柱位动态", {}).get("月柱", {})
    for tier_items in pillar_data.values():
        if not isinstance(tier_items, list):
            continue
        for item in tier_items:
            if item.get("类型") in {"六合", "三合", "三会"}:
                if item.get("强度") in ACTIVE_STRENGTHS:
                    effect = {
                        "作用类型": "事业突破",
                        "解读": "大运生合月柱，职业助力到位、人脉畅通，事业晋升或转机在此阶段实现。",
                        "互动类型": "六合/三合",
                        "强度": "显著影响",
                    }
                    return [_modulate_career_effect_by_constitution(effect, dm_score)]
    return []


def _cycle_yin_star_active(decade: dict, dm_score: int) -> list:
    """Education/mentorship phase when cycle brings 印星"""
    run_zhu = decade.get("运柱", {})
    shi_shen = run_zhu.get("十神", {})
    if shi_shen.get("天干", {}).get("十神") in YIN_STARS:
        effect = {
            "作用类型": "学习充电",
            "解读": "大运印星激活，进修或导师机缘到来，职业停驻以积累知识，为下一步突破储能。",
            "互动类型": "印星到位",
            "强度": "中等影响",
        }
        return [_modulate_career_effect_by_constitution(effect, dm_score)]
    return []


def _cycle_shi_shang_active(decade: dict, dm_score: int) -> list:
    """Creative phase when cycle brings 食伤"""
    run_zhu = decade.get("运柱", {})
    shi_shen = run_zhu.get("十神", {})
    if shi_shen.get("天干", {}).get("十神") in FOOD_GOD_HURT_OFFICER:
        effect = {
            "作用类型": "创业机遇",
            "解读": "大运食伤激活，创意或创业窗口开启，独立创业或个人品牌建设在此阶段可行性高。",
            "互动类型": "食伤到位",
            "强度": "中等影响",
        }
        return [_modulate_career_effect_by_constitution(effect, dm_score)]
    return []


def _cycle_void_career(
    decade: dict, csp: dict, void_branch_chars: set, dm_score: int
) -> list:
    """Career hollowed when cycle branch falls in natal 旬空 positions."""
    if not csp["all"]:
        return []
    run_branch = decade.get("运柱", {}).get("地支", "")
    if run_branch and run_branch in void_branch_chars:
        effect = {
            "作用类型": "事业停滞",
            "解读": "大运落旬空，职业推进受阻、机会虚幻，事业进展缓慢，此阶段以守成为主。",
            "互动类型": "旬空",
            "强度": "中等影响",
        }
        return [_modulate_career_effect_by_constitution(effect, dm_score)]
    return []


def _cycle_fanyin_career(decade: dict, branch_chars: dict, dm_score: int) -> list:
    """Career upheaval when cycle is opposite of Month or Day branch (反吟)"""
    run_zhu = decade.get("运柱", {})
    run_branch = run_zhu.get("地支")
    if not run_branch:
        return []
    # Map of opposite branches
    opposite_map = {
        "子": "午",
        "午": "子",
        "丑": "未",
        "未": "丑",
        "寅": "申",
        "申": "寅",
        "卯": "酉",
        "酉": "卯",
        "辰": "戌",
        "戌": "辰",
        "巳": "亥",
        "亥": "巳",
    }
    opposite = opposite_map.get(run_branch)
    if opposite:
        if opposite == branch_chars.get("月支") or opposite == branch_chars.get("日支"):
            effect = {
                "作用类型": "事业反吟",
                "解读": "大运反吟，职业方向翻转或重大调整，旧的事业框架被打破，需重新定位与出发。",
                "互动类型": "反吟",
                "强度": "显著影响",
            }
            return [_modulate_career_effect_by_constitution(effect, dm_score)]
    return []


def _cycle_fuyin_career(
    decade: dict, branch_chars: dict, csp: dict, dm_score: int
) -> list:
    """Career stagnation when cycle is same as Month or Day branch (伏吟)"""
    if not csp["all"]:
        return []
    run_zhu = decade.get("运柱", {})
    run_branch = run_zhu.get("地支")
    if not run_branch:
        return []
    if run_branch == branch_chars.get("月支") or run_branch == branch_chars.get("日支"):
        effect = {
            "作用类型": "事业伏吟",
            "解读": "大运伏吟，职业陷入重复循环，进展停滞、机会难新，此阶段宜耐心积累而非冒进。",
            "互动类型": "伏吟",
            "强度": "中等影响",
        }
        return [_modulate_career_effect_by_constitution(effect, dm_score)]
    return []


def _get_cycle_career_events(
    decade: dict, csp: dict, branch_chars: dict, voided_branches: set, dm_score: int
) -> list:
    """Aggregate all cycle events for a 大运 decade, modulated by constitutional strength."""
    # Convert position keys ("年支") to actual branch chars ("午") for cycle void check
    void_branch_chars = {branch_chars[k] for k in voided_branches if k in branch_chars}
    events = []
    events.extend(_cycle_guan_sha_arrives(decade, csp, dm_score))
    events.extend(_cycle_clashes_career(decade, dm_score))
    events.extend(_cycle_activates_career(decade, dm_score))
    events.extend(_cycle_yin_star_active(decade, dm_score))
    events.extend(_cycle_shi_shang_active(decade, dm_score))
    events.extend(_cycle_void_career(decade, csp, void_branch_chars, dm_score))
    events.extend(_cycle_fanyin_career(decade, branch_chars, dm_score))
    events.extend(_cycle_fuyin_career(decade, branch_chars, csp, dm_score))
    return events


# ── Synthesis ──────────────────────────────────────────────────────────────────


def _synthesize_career_patterns(fired_patterns: dict) -> dict:
    """
    Synthesize fired patterns into:
    - 主格局 (primary pattern name) or None
    - 辅助来源 (list of supplementary names)
    - 风险因素 (list of risk names)
    - 综合解读 (synthesized narrative)
    """
    primary = None
    for p_id in fired_patterns:
        if p_id in PRIMARY_PATTERNS:
            primary = fired_patterns[p_id].get("格局名称")
            break

    supp = [
        fired_patterns[p_id].get("格局名称")
        for p_id in fired_patterns
        if p_id in SUPPLEMENTARY_IDS
    ]
    risk = [
        fired_patterns[p_id].get("格局名称")
        for p_id in fired_patterns
        if p_id in RISK_IDS
    ]

    has_supp = bool(supp)
    has_risk = bool(risk)

    template_dict = _SYNTH.get(primary, _SYNTH_DEFAULT if primary else _SYNTH[None])
    template = template_dict.get(
        (has_supp, has_risk), _SYNTH_DEFAULT[(has_supp, has_risk)]
    )

    supp_str = "、".join(supp) if supp else ""
    risk_str = "、".join(risk) if risk else ""
    synth_text = template.format(
        supp_str=supp_str,
        risk_str=risk_str,
        anchor_name=primary or "命盘",
    )

    return {
        "主格局": primary,
        "辅助来源": supp,
        "风险因素": risk,
        "综合解读": synth_text,
    }


# ── Main extraction function ───────────────────────────────────────────────────


def extract_career_insights(raw_data: dict) -> dict:
    """
    Main extraction API. Called by AstroDataLLMFormatter.
    """
    # Extract data
    shi_shen = raw_data.get("shi_shen", {}).get("十神", {})
    day_master = raw_data.get("day_master", {}).get("日主", {})
    bazi = raw_data.get("bazi", {})
    wu_xing = raw_data.get("wu_xing", {}).get("五行力量", {})
    da_yun = raw_data.get("da_yun", {})
    interactions = raw_data.get("interactions", {})
    xun_kong = raw_data.get("xun_kong", {})
    shen_sha_raw = raw_data.get("shen_sha", {}).get("神煞", {})

    dm_element = day_master.get("五行")
    dm_stem = day_master.get("天干")
    dm_score = day_master.get("强弱分数", 0)

    # Organize shen_sha by pillar
    shen_sha = {}
    for pillar in PILLARS:
        pillar_key = pillar
        shen_sha[pillar] = shen_sha_raw.get("柱位神煞", {}).get(pillar_key, {})

    # Get positional data
    csp = _get_career_star_positions(shi_shen, bazi)
    yin_pos = _get_yin_stars_positions(shi_shen)
    food_pos = _get_food_god_hurt_officer_positions(shi_shen)
    peer_pos = _get_peer_stars_positions(shi_shen)

    # Get wealth positions (for no_career_star pattern check)
    wealth_pos = {}
    for pillar in PILLARS:
        p = shi_shen.get(pillar, {})
        if p.get("天干十神") in WEALTH_STARS:
            wealth_pos[pillar] = True
    wealth_pos = {"all": list(wealth_pos.keys())}

    branch_chars = _get_branch_chars(bazi)
    voided_branches = _void_branch_positions(branch_chars, xun_kong)
    current_decade = _get_current_decade(da_yun)

    # Fire all pattern checkers
    fired = {}

    # Tier 1
    if p := _pattern_career_star_visible(csp):
        fired["career_star_visible"] = {
            **p,
            "格局编号": "career_star_visible",
            "格局名称": "官星透干",
        }
    if p := _pattern_career_star_hidden(csp):
        fired["career_star_hidden"] = {
            **p,
            "格局编号": "career_star_hidden",
            "格局名称": "官星藏支",
        }
    if p := _pattern_career_star_strong(wu_xing, csp, dm_score):
        fired["career_star_strong"] = {
            **p,
            "格局编号": "career_star_strong",
            "格局名称": "官星旺盛",
        }
    if p := _pattern_career_star_weak(wu_xing, csp, dm_score):
        fired["career_star_weak"] = {
            **p,
            "格局编号": "career_star_weak",
            "格局名称": "官星微弱",
        }
    if p := _pattern_no_career_star(csp, food_pos, wealth_pos, wu_xing, dm_element):
        fired["no_career_star"] = {
            **p,
            "格局编号": "no_career_star",
            "格局名称": "无官无杀",
        }
    if p := _pattern_seal_support_present(yin_pos, wu_xing, dm_element):
        fired["seal_support_present"] = {
            **p,
            "格局编号": "seal_support_present",
            "格局名称": "印星有力",
        }
    if p := _pattern_seal_support_weak(yin_pos, wu_xing, dm_element):
        fired["seal_support_weak"] = {
            **p,
            "格局编号": "seal_support_weak",
            "格局名称": "印星不足",
        }

    # Tier 1b
    if p := _pattern_official_career(csp, dm_score):
        fired["official_career"] = {
            **p,
            "格局编号": "official_career",
            "格局名称": "正官主导",
        }
    if p := _pattern_killer_career(csp, dm_score):
        fired["killer_career"] = {
            **p,
            "格局编号": "killer_career",
            "格局名称": "七杀主导",
        }

    # Tier 2
    if p := _pattern_expression_career(food_pos, wu_xing, dm_element, dm_score):
        fired["expression_career"] = {
            **p,
            "格局编号": "expression_career",
            "格局名称": "食伤主职",
        }
    if p := _pattern_expression_controls_killer(
        food_pos, csp["killer"], wu_xing, dm_element, dm_score
    ):
        fired["expression_controls_killer"] = {
            **p,
            "格局编号": "expression_controls_killer",
            "格局名称": "食伤制杀",
        }
    if p := _pattern_peer_career(peer_pos, wu_xing, dm_element):
        fired["peer_career"] = {**p, "格局编号": "peer_career", "格局名称": "比劫同道"}
    if p := _pattern_wealth_from_career(shi_shen):
        fired["wealth_from_career"] = {
            **p,
            "格局编号": "wealth_from_career",
            "格局名称": "财星入职柱",
        }
    if p := _pattern_career_combined_with_dm(interactions, dm_stem, csp):
        fired["career_combined_with_dm"] = {
            **p,
            "格局编号": "career_combined_with_dm",
            "格局名称": "日主合官",
        }
    if p := _pattern_officer_seal_chain(csp, yin_pos, wu_xing, dm_element):
        fired["officer_seal_chain"] = {
            **p,
            "格局编号": "officer_seal_chain",
            "格局名称": "官印相生",
        }

    # Tier 3
    if p := _pattern_family_career(shi_shen):
        fired["family_career"] = {
            **p,
            "格局编号": "family_career",
            "格局名称": "祖业仕途",
        }
    if p := _pattern_midlife_career_peak(shi_shen, wu_xing, dm_element, csp, dm_score):
        fired["midlife_career_peak"] = {
            **p,
            "格局编号": "midlife_career_peak",
            "格局名称": "月令仕途旺",
        }
    if p := _pattern_self_employed(shi_shen):
        fired["self_employed"] = {
            **p,
            "格局编号": "self_employed",
            "格局名称": "自主创业",
        }
    if p := _pattern_day_pillar_career(shi_shen):
        fired["day_pillar_career"] = {
            **p,
            "格局编号": "day_pillar_career",
            "格局名称": "日坐官星",
        }
    if p := _pattern_late_career_success(shi_shen):
        fired["late_career_success"] = {
            **p,
            "格局编号": "late_career_success",
            "格局名称": "晚年仕途",
        }
    if p := _pattern_career_void(csp, voided_branches):
        fired["career_void"] = {**p, "格局编号": "career_void", "格局名称": "官星落空"}

    # Tier 4
    if p := _pattern_career_clashed(csp, interactions, branch_chars, dm_score):
        fired["career_clashed"] = {
            **p,
            "格局编号": "career_clashed",
            "格局名称": "官星受冲",
        }
    if p := _pattern_career_harmed(csp, interactions, dm_score):
        fired["career_harmed"] = {
            **p,
            "格局编号": "career_harmed",
            "格局名称": "官星受害",
        }
    if p := _pattern_career_punished(csp, interactions, dm_score):
        fired["career_punished"] = {
            **p,
            "格局编号": "career_punished",
            "格局名称": "官星受刑",
        }
    if p := _pattern_month_pillar_career_clashed(interactions):
        fired["month_pillar_career_clashed"] = {
            **p,
            "格局编号": "month_pillar_career_clashed",
            "格局名称": "月柱职业宫受冲",
        }
    if p := _pattern_month_pillar_career_harmonious(interactions):
        fired["month_pillar_career_harmonious"] = {
            **p,
            "格局编号": "month_pillar_career_harmonious",
            "格局名称": "月柱职业宫和谐",
        }
    if p := _pattern_career_activated_now(current_decade, csp):
        fired["career_activated_now"] = {
            **p,
            "格局编号": "career_activated_now",
            "格局名称": "当运事业星",
        }

    # Tier 5
    if p := _pattern_leader_star_present(shen_sha):
        fired["leader_star_present"] = {
            **p,
            "格局编号": "leader_star_present",
            "格局名称": "将星入命",
        }
    if p := _pattern_fierce_leader(shen_sha):
        fired["fierce_leader"] = {
            **p,
            "格局编号": "fierce_leader",
            "格局名称": "魁罡主职",
        }
    if p := _pattern_noble_support(shen_sha):
        fired["noble_support"] = {
            **p,
            "格局编号": "noble_support",
            "格局名称": "天乙贵人助仕",
        }
    if p := _pattern_academic_star(shen_sha):
        fired["academic_star"] = {
            **p,
            "格局编号": "academic_star",
            "格局名称": "文昌主职",
        }
    if p := _pattern_salary_star(shen_sha):
        fired["salary_star"] = {**p, "格局编号": "salary_star", "格局名称": "禄神入命"}
    if p := _pattern_travel_career(shen_sha):
        fired["travel_career"] = {
            **p,
            "格局编号": "travel_career",
            "格局名称": "驿马仕途",
        }

    # Synthesize
    synthesis = _synthesize_career_patterns(fired)

    # Build natal patterns list
    natal_patterns = list(fired.values())

    # Process cycles
    cycles = da_yun.get("大运", {}).get("大运周期", [])
    cycle_effects = []
    today = date.today()
    for cycle in cycles[1:]:  # Skip placeholder
        events = _get_cycle_career_events(
            cycle, csp, branch_chars, voided_branches, dm_score
        )
        if events:  # Only include decades with career effects
            # Compute state: 当运 if True, 已过 if end_year < today, else 未来
            if cycle.get("当运"):
                state = "当运"
            elif cycle.get("结束年份", 9999) < today.year:
                state = "已过"
            else:
                state = "未来"
            cycle_effects.append(
                {
                    "大运": cycle.get(
                        "周期", cycle.get("运柱", {}).get("显示名称", "")
                    ),
                    "运势": state,
                    "职业作用": events,
                }
            )

    # Build output
    output = {
        "事业综合评估": synthesis,
        "命盘职业格局": natal_patterns,
        "大运职业动态": cycle_effects,
    }

    if not natal_patterns:
        output["无格局提示"] = "命盘职业格局不显著，事业走向主要依赖大运与自身努力。"
    else:
        output["无格局提示"] = None

    return output


# ============================================================================
# EXECUTION
# python -m src.astronomer_calculations.interpretive_insights_career
# ============================================================================

if __name__ == "__main__":
    import json
    from datetime import datetime as dt
    from src.astronomer_calculations.solar_lunar_time import get_true_solar_time
    from src.services.astronomer_data_aggregator import AstroDataAggregator
    from src.utils.logging import configure_logging, get_logger

    configure_logging()
    logger = get_logger(__name__)

    # Example subjects to test career insights extraction
    subjects = {
        "Desmond": (dt(1985, 11, 25, 17, 7, 0), 1.3253, 103.808053, 1),
    }

    for name, (birthday, lat, lon, gender) in subjects.items():
        logger.info("=" * 80)
        logger.info(
            "Career Insights for: %s  (%s)", name, birthday.strftime("%Y-%m-%d %H:%M")
        )
        logger.info("=" * 80)

        tst_birthday, _ = get_true_solar_time(birthday, lat, lon)
        lunar_birthday = tst_birthday.getLunar()

        raw_data = AstroDataAggregator().collect_data(
            lunar_birthday,
            birth_datetime=birthday,
            latitude=lat,
            longitude=lon,
            gender=gender,
        )

        # Extract career insights using all 33 patterns across 5 tiers
        career_insights = extract_career_insights(raw_data)

        logger.info(json.dumps(career_insights, ensure_ascii=False, indent=2))
