# ============================================================================
# IMPORTS AND DEPENDENCIES
# ============================================================================
from dataclasses import dataclass
from enum import Enum
from typing import List, Dict, Optional, Tuple, Any
from lunar_python import Lunar

# Import shared enums and lookup tables from wu_xing.py (module-level only)
from src.astronomer_calculations.wu_xing import (
    Element,
    Stem,
    Branch,
    STEM_ELEMENT,
    BRANCH_HIDDEN,
    SHENG_WANG_TABLE,
    get_seasonal_factors,
)

# Import helper functions from cycle_wu_xing.py
from src.astronomer_calculations.cycle_wu_xing import (
    string_to_stem,
    string_to_branch,
)

# Import ten god lookup from cycle_shi_shen.py
from src.astronomer_calculations.cycle_shi_shen import get_shi_shen_for_stem_pair

class SeasonalState(Enum):
    WANG = "旺"   # in season
    XIANG = "相"   # generated by season
    XIU = "休"     # generates season
    QIU = "囚"     # controlled by season
    SI = "死"      # controlled by season

class LifeStage(Enum):
    CHANG_SHENG = "长生"
    MU_YU = "沐浴"
    GUAN_DAI = "冠带"
    LIN_GUAN = "临官"
    DI_WANG = "帝旺"
    SHUAI = "衰"
    BING = "病"
    SI = "死"
    MU = "墓"
    JUE = "绝"
    TAI = "胎"
    YANG = "养"

class RootStrength(Enum):
    STRONG = "强根"
    WEAK = "弱根"
    NONE = "无根"



# Interactions
SIX_COMBINATIONS = {
    (Branch.ZI, Branch.CHOU): Element.EARTH,
    (Branch.YIN, Branch.HAI): Element.WOOD,
    (Branch.MAO, Branch.XU): Element.FIRE,
    (Branch.CHEN, Branch.YOU): Element.METAL,
    (Branch.SI, Branch.SHEN): Element.WATER,
    (Branch.WU, Branch.WEI): Element.FIRE,
}
THREE_HARMONIES = {
    Element.WATER: (Branch.ZI, [Branch.SHEN, Branch.ZI, Branch.CHEN]),
    Element.WOOD: (Branch.MAO, [Branch.HAI, Branch.MAO, Branch.WEI]),
    Element.FIRE: (Branch.WU, [Branch.YIN, Branch.WU, Branch.XU]),
    Element.METAL: (Branch.YOU, [Branch.SI, Branch.YOU, Branch.CHOU]),
}
CLASH_PAIRS = {
    (Branch.ZI, Branch.WU),
    (Branch.CHOU, Branch.WEI),
    (Branch.YIN, Branch.SHEN),
    (Branch.MAO, Branch.YOU),
    (Branch.CHEN, Branch.XU),
    (Branch.SI, Branch.HAI),
}
PUNISHMENTS = {
    "寅巳申": [Branch.YIN, Branch.SI, Branch.SHEN],
    "丑戌未": [Branch.CHOU, Branch.XU, Branch.WEI],
    "子卯": [Branch.ZI, Branch.MAO],
}
HARMS = {
    (Branch.ZI, Branch.WEI),
    (Branch.CHOU, Branch.WU),
    (Branch.YIN, Branch.SI),
    (Branch.MAO, Branch.CHEN),
    (Branch.SHEN, Branch.HAI),
    (Branch.YOU, Branch.XU),
}

# ============================================================================
# PILLAR DATA CLASS
# ============================================================================

@dataclass
class Pillar:
    position: str  # "year", "month", "day", "hour", or cycle type like "da_yun"
    stem: Optional[Stem]
    branch: Optional[Branch]
    is_cycle: bool = False  # True if this is a cycle pillar

# ============================================================================
# WU XING ASSESSOR
# ============================================================================

class WuXingAssessor:
    """
    Qualitative assessment of Five Element dynamics in a BaZi chart,
    optionally including a cycle pillar (Da Yun, Liu Nian, etc.).
    """

    def __init__(self, lunar_birthday: Lunar):
        """
        Initialize with a lunar birthday. Extracts natal pillars.
        """
        self.lunar = lunar_birthday
        self.natal_pillars: List[Pillar] = self._extract_natal_pillars()
        self.cycle_pillar: Optional[Pillar] = None
        self.cycle_type: Optional[str] = None

    def _extract_natal_pillars(self) -> List[Pillar]:
        bazi = self.lunar.getEightChar()
        pillars = []
        positions = ["year", "month", "day", "hour"]
        # Map position to the correct method name part
        method_part = {
            "year": "Year",
            "month": "Month",
            "day": "Day",
            "hour": "Time",
        }
        for pos in positions:
            part = method_part[pos]
            stem_str = getattr(bazi, f"get{part}Gan")()
            branch_str = getattr(bazi, f"get{part}Zhi")()
            stem = string_to_stem(stem_str)
            branch = string_to_branch(branch_str)
            pillars.append(Pillar(pos, stem, branch))
        return pillars

    def add_cycle_pillar(self, stem: str, branch: str, cycle_type: str = "da_yun"):
        """
        Add a cycle pillar for analysis.
        cycle_type: e.g., "da_yun", "liu_nian", "xiao_yun", "liu_yue"
        """
        self.cycle_pillar = Pillar(
            position=cycle_type,
            stem=string_to_stem(stem),
            branch=string_to_branch(branch),
            is_cycle=True,
        )
        self.cycle_type = cycle_type

    # ------------------------------------------------------------------------
    # Core analysis methods
    # ------------------------------------------------------------------------

    def analyze(self) -> Dict[str, Any]:
        """
        Perform full qualitative analysis.
        Returns a structured dictionary.
        """
        result = {
            "日主": self._analyze_day_master(),
            "四柱状态": self._analyze_natal_pillars(),
            "相互作用": self._detect_interactions(),
        }

        if self.cycle_pillar:
            result["流年/大运"] = self._analyze_cycle_pillar()
            # Also include interactions involving cycle pillar
            cycle_interactions = self._detect_cycle_interactions()
            if cycle_interactions:
                result["相互作用"]["与大运/流年"] = cycle_interactions

        # Generate a synthesized judgment
        result["综合判断"] = self._synthesize(result)

        return result

    def _analyze_day_master(self) -> Dict:
        """Analyze the Day Master (日主) itself."""
        day_pillar = next(p for p in self.natal_pillars if p.position == "day")
        stem = day_pillar.stem
        branch = day_pillar.branch
        elem = STEM_ELEMENT[stem]
        # Determine polarity (yang if odd index in list)
        # Assuming Stem enum order matches traditional sequence
        stems_list = list(Stem)
        idx = stems_list.index(stem) + 1
        polarity = "阳" if idx % 2 == 1 else "阴"

        # Seasonal state of the day master's element
        month_pillar = next(p for p in self.natal_pillars if p.position == "month")
        seasonal_state = self._get_seasonal_state(elem, month_pillar.branch)

        # Life stage of the day master's stem relative to its own branch
        life_stage = self._get_life_stage(stem, branch)

        # Rooting of the day master's stem in all branches
        root = self._get_rooting(stem, [p.branch for p in self.natal_pillars])

        return {
            "天干": stem.value,
            "五行": elem.value,
            "阴阳": polarity,
            "季节状态": seasonal_state.value,
            "十二长生": life_stage.value,
            "通根": root.value,
        }

    def _analyze_natal_pillars(self) -> Dict[str, Dict]:
        """Analyze each of the four natal pillars."""
        result = {}
        for pillar in self.natal_pillars:
            result[pillar.position + "柱"] = self._analyze_single_pillar(pillar)
        return result

    def _analyze_single_pillar(self, pillar: Pillar) -> Dict:
        """Analyze a single pillar (can be natal or cycle)."""
        stem_analysis = None
        branch_analysis = None

        if pillar.stem:
            elem = STEM_ELEMENT[pillar.stem]
            month_branch = next(p for p in self.natal_pillars if p.position == "month").branch
            seasonal_state = self._get_seasonal_state(elem, month_branch)
            life_stage = self._get_life_stage(pillar.stem, pillar.branch) if pillar.branch else None
            # Rooting of this stem in all natal branches (excluding cycle)
            all_natal_branches = [p.branch for p in self.natal_pillars]
            root = self._get_rooting(pillar.stem, all_natal_branches)
            # If this is a cycle pillar, also consider its own branch as a potential root
            if pillar.is_cycle and pillar.branch:
                # We might include the cycle's own branch for rooting, but traditionally a stem roots in branches of the natal chart.
                # For simplicity, we keep only natal branches.
                pass

            stem_analysis = {
                "天干": pillar.stem.value,
                "五行": elem.value,
                "季节状态": seasonal_state.value,
                "十二长生": life_stage.value if life_stage else None,
                "通根": root.value,
            }

        if pillar.branch:
            hidden_stems = []
            for hs, depth in BRANCH_HIDDEN.get(pillar.branch, []):
                elem = STEM_ELEMENT[hs]
                hidden_stems.append({
                    "藏干": hs.value,
                    "五行": elem.value,
                    "深度": depth,
                })
            branch_analysis = {
                "地支": pillar.branch.value,
                "藏干": hidden_stems,
            }

        return {
            "天干分析": stem_analysis,
            "地支分析": branch_analysis,
        }

    def _analyze_cycle_pillar(self) -> Dict:
        """Analyze the added cycle pillar."""
        if not self.cycle_pillar:
            return {}
        analysis = self._analyze_single_pillar(self.cycle_pillar)

        # Add ten gods relationship with Day Master
        day_master_stem = next(p for p in self.natal_pillars if p.position == "day").stem
        if self.cycle_pillar.stem and day_master_stem:
            ten_god = self._get_ten_god(self.cycle_pillar.stem, day_master_stem)
            analysis["对日主十神"] = ten_god

        return analysis

    # ------------------------------------------------------------------------
    # Helper methods for qualitative judgments
    # ------------------------------------------------------------------------

    def _get_seasonal_state(self, element: Element, month_branch: Branch) -> SeasonalState:
        """
        Determine the seasonal state (旺相休囚死) of an element based on the month branch.
        Uses get_seasonal_factors from wu_xing.py which provides authoritative seasonal mappings.
        """
        seasonal = get_seasonal_factors(month_branch)
        state_str = seasonal.states.get(element, "囚")

        # Map string state to SeasonalState enum
        state_map = {
            "旺": SeasonalState.WANG,
            "相": SeasonalState.XIANG,
            "休": SeasonalState.XIU,
            "囚": SeasonalState.QIU,
            "死": SeasonalState.SI,
        }
        return state_map.get(state_str, SeasonalState.QIU)

    def _get_life_stage(self, stem: Stem, branch: Branch) -> Optional[LifeStage]:
        """Retrieve the 12 life stage of a stem relative to a branch."""
        stage_str = SHENG_WANG_TABLE.get(stem, {}).get(branch)
        if stage_str:
            # Map string to LifeStage enum
            for stage in LifeStage:
                if stage.value == stage_str:
                    return stage
        return None

    def _get_rooting(self, stem: Stem, branches: List[Branch]) -> RootStrength:
        """
        Determine if the stem has a root in the given branches.
        A strong root: the primary hidden stem (depth 1.0) of a branch matches the stem's element.
        A weak root: any secondary hidden stem (depth < 1.0) matches.
        No root: otherwise.
        """
        elem = STEM_ELEMENT[stem]
        for branch in branches:
            hidden = BRANCH_HIDDEN.get(branch, [])
            for idx, (hs, depth) in enumerate(hidden):
                if STEM_ELEMENT[hs] == elem:
                    # Primary hidden stem = strong root; any later occurrence = weak root
                    return RootStrength.STRONG if idx == 0 else RootStrength.WEAK
        return RootStrength.NONE

    def _get_ten_god(self, cycle_stem: Stem, day_stem: Stem) -> str:
        """
        Return the ten god relationship between cycle stem and day master.
        Uses LunarUtil.SHI_SHEN lookup for complete 100-pair mapping (all day masters).
        """
        return get_shi_shen_for_stem_pair(day_stem.value, cycle_stem.value)

    # ------------------------------------------------------------------------
    # Interaction detection
    # ------------------------------------------------------------------------

    def _detect_interactions(self) -> Dict[str, List[Dict]]:
        """
        Detect interactions among natal pillars.
        Returns a dict of lists: 六合, 三合, 六冲, 刑, 害.
        """
        branches = [p.branch for p in self.natal_pillars if p.branch]
        interactions = {
            "六合": [],
            "三合": [],
            "六冲": [],
            "刑": [],
            "害": [],
        }

        # 六合 (six combinations) - pairs
        for i, b1 in enumerate(branches):
            for b2 in branches[i+1:]:
                if (b1, b2) in SIX_COMBINATIONS or (b2, b1) in SIX_COMBINATIONS:
                    elem = SIX_COMBINATIONS.get((b1, b2)) or SIX_COMBINATIONS.get((b2, b1))
                    desc = f"{b1.value}{b2.value}六合化{elem.value}"
                    interactions["六合"].append({
                        "类型": "六合",
                        "参与地支": [b1.value, b2.value],
                        "化神": elem.value,
                        "描述": desc,
                    })

        # 三合 (three harmonies) - triplets
        for elem, (hub, triplet) in THREE_HARMONIES.items():
            present = [b for b in branches if b in triplet]
            if len(present) == 3:
                desc = f"{''.join([b.value for b in present])}三合{elem.value}局"
                interactions["三合"].append({
                    "类型": "三合",
                    "参与地支": [b.value for b in present],
                    "化神": elem.value,
                    "描述": desc,
                })

        # 六冲 (clashes) - pairs
        for i, b1 in enumerate(branches):
            for b2 in branches[i+1:]:
                if (b1, b2) in CLASH_PAIRS or (b2, b1) in CLASH_PAIRS:
                    desc = f"{b1.value}{b2.value}相冲"
                    interactions["六冲"].append({
                        "类型": "六冲",
                        "参与地支": [b1.value, b2.value],
                        "描述": desc,
                    })

        # 刑 (punishments)
        # Triple punishments
        for name, triplet in PUNISHMENTS.items():
            if len(triplet) == 3:
                present = [b for b in branches if b in triplet]
                if len(present) == 3:
                    desc = f"{''.join([b.value for b in present])}{name}"
                    interactions["刑"].append({
                        "类型": "三刑",
                        "参与地支": [b.value for b in present],
                        "描述": desc,
                    })
                elif len(present) == 2:
                    desc = f"{''.join([b.value for b in present])}{name}半刑"
                    interactions["刑"].append({
                        "类型": "半刑",
                        "参与地支": [b.value for b in present],
                        "描述": desc,
                    })
            elif len(triplet) == 2:  # 子卯刑
                b1, b2 = triplet[0], triplet[1]
                if b1 in branches and b2 in branches:
                    desc = f"{b1.value}{b2.value}相刑"
                    interactions["刑"].append({
                        "类型": "相刑",
                        "参与地支": [b1.value, b2.value],
                        "描述": desc,
                    })

        # 害 (harms)
        for i, b1 in enumerate(branches):
            for b2 in branches[i+1:]:
                if (b1, b2) in HARMS or (b2, b1) in HARMS:
                    desc = f"{b1.value}{b2.value}相害"
                    interactions["害"].append({
                        "类型": "六害",
                        "参与地支": [b1.value, b2.value],
                        "描述": desc,
                    })

        return interactions

    def _detect_cycle_interactions(self) -> Dict[str, List[Dict]]:
        """
        Detect interactions between the cycle pillar and all natal pillars.
        """
        if not self.cycle_pillar or not self.cycle_pillar.branch:
            return {}
        cycle_branch = self.cycle_pillar.branch
        natal_branches = [p.branch for p in self.natal_pillars if p.branch]
        interactions = {
            "六合": [],
            "三合": [],
            "六冲": [],
            "刑": [],
            "害": [],
        }

        # Check each interaction with cycle branch
        for nb in natal_branches:
            # 六合
            if (cycle_branch, nb) in SIX_COMBINATIONS or (nb, cycle_branch) in SIX_COMBINATIONS:
                elem = SIX_COMBINATIONS.get((cycle_branch, nb)) or SIX_COMBINATIONS.get((nb, cycle_branch))
                desc = f"{cycle_branch.value}{nb.value}六合化{elem.value}"
                interactions["六合"].append({
                    "类型": "六合",
                    "参与地支": [cycle_branch.value, nb.value],
                    "化神": elem.value,
                    "描述": desc,
                })

            # 六冲
            if (cycle_branch, nb) in CLASH_PAIRS or (nb, cycle_branch) in CLASH_PAIRS:
                desc = f"{cycle_branch.value}{nb.value}相冲"
                interactions["六冲"].append({
                    "类型": "六冲",
                    "参与地支": [cycle_branch.value, nb.value],
                    "描述": desc,
                })

            # 害
            if (cycle_branch, nb) in HARMS or (nb, cycle_branch) in HARMS:
                desc = f"{cycle_branch.value}{nb.value}相害"
                interactions["害"].append({
                    "类型": "六害",
                    "参与地支": [cycle_branch.value, nb.value],
                    "描述": desc,
                })

        # 三合 - check if cycle branch completes a triplet with two natal branches
        for elem, (hub, triplet) in THREE_HARMONIES.items():
            present_natal = [b for b in natal_branches if b in triplet]
            if cycle_branch in triplet and len(present_natal) >= 2:
                all_present = present_natal + [cycle_branch]
                if len(all_present) == 3:
                    desc = f"{''.join([b.value for b in all_present])}三合{elem.value}局"
                    interactions["三合"].append({
                        "类型": "三合",
                        "参与地支": [b.value for b in all_present],
                        "化神": elem.value,
                        "描述": desc,
                    })

        # 刑 - check punishments involving cycle branch
        # Triple punishments
        for name, triplet in PUNISHMENTS.items():
            if len(triplet) == 3:
                present = [b for b in natal_branches if b in triplet]
                if cycle_branch in triplet:
                    present_with_cycle = present + [cycle_branch]
                    present_with_cycle = list(set(present_with_cycle))  # dedup
                    if len(present_with_cycle) >= 2:
                        desc = f"{''.join([b.value for b in present_with_cycle])}{name}"
                        interactions["刑"].append({
                            "类型": "三刑",
                            "参与地支": [b.value for b in present_with_cycle],
                            "描述": desc,
                        })
            elif len(triplet) == 2:  # 子卯刑
                b1, b2 = triplet[0], triplet[1]
                if cycle_branch in (b1, b2):
                    other = b2 if cycle_branch == b1 else b1
                    if other in natal_branches:
                        desc = f"{cycle_branch.value}{other.value}相刑"
                        interactions["刑"].append({
                            "类型": "相刑",
                            "参与地支": [cycle_branch.value, other.value],
                            "描述": desc,
                        })

        return interactions

    # ------------------------------------------------------------------------
    # Synthesis
    # ------------------------------------------------------------------------

    def _synthesize(self, analysis: Dict) -> str:
        """
        Generate a human-readable synthesis based on all facts.
        This is a simplified example – can be expanded with more rules.
        """
        sentences = []

        day_master = analysis["日主"]
        sentences.append(f"日主为{day_master['天干']}{day_master['五行']}{day_master['阴阳']}，"
                         f"季节状态{day_master['季节状态']}，{day_master['十二长生']}，"
                         f"{day_master['通根']}。")

        # Check if cycle pillar exists and add key interactions
        if "流年/大运" in analysis:
            cycle = analysis["流年/大运"]
            if "对日主十神" in cycle:
                sentences.append(f"大运/流年天干对日主为{cycle['对日主十神']}。")

            cycle_inter = analysis["相互作用"].get("与大运/流年", {})
            if cycle_inter.get("六冲"):
                for item in cycle_inter["六冲"]:
                    sentences.append(f"发生{item['描述']}，主变动。")
            if cycle_inter.get("三合"):
                for item in cycle_inter["三合"]:
                    sentences.append(f"形成{item['描述']}，增强{item['化神']}力量。")
            if cycle_inter.get("六合"):
                for item in cycle_inter["六合"]:
                    sentences.append(f"形成{item['描述']}，转化能量。")

        # If no major interactions, state general condition
        if not sentences:
            sentences.append("五行基本平衡，无明显冲合。")

        return " ".join(sentences)

# --- EXECUTION ---

if __name__ == "__main__":
    import json
    from lunar_python import Solar
    from datetime import datetime
    from src.utils.logging import configure_logging, get_logger
    from src.astronomer_calculations.solar_lunar_time import get_true_solar_time

    logging = configure_logging()
    logger = get_logger(__name__)

    # python -m src.astronomer_calculations.qualitative_wu_xing

    # # Desmond's birthday example
    solar_birthday = Solar.fromYmdHms(1985, 11, 25, 17, 7, 0)  # Create solar date
    datetime_birthday = datetime(1985, 11, 25, 17, 7, 0)  # Create datetime object
    tst_birthday, _ = get_true_solar_time(
        datetime_birthday, 1.3253, 103.808053
    )  # Get true solar time

    # # Corinne's birthday example
    # solar_birthday= Solar.fromYmdHms(1987, 6, 3, 12, 6, 0)  # Create solar date June 3, 1987 at 12:06 PM
    # tst_birthday, inputs_report = get_true_solar_time(datetime(1987, 6, 3, 12, 6, 0), 1.4759, 103.808053)  # Get true solar time for the birthday

    # # Lara's birthday example
    # solar_birthday = Solar.fromYmdHms(
    #     2025, 7, 31, 9, 10, 0
    # )  # Create solar date June 3, 1987 at 12:06 PM
    # tst_birthday, inputs_report = get_true_solar_time(
    #     datetime(2025, 7, 31, 9, 10, 0), 1.3253, 103.808053
    # )

    logger.info("阳历生日: " + solar_birthday.toYmdHms())
    logger.info("真太阳时生日: " + tst_birthday.toYmdHms())

    lunar_birthday = tst_birthday.getLunar()  # Convert to lunar calendar

    bazi = lunar_birthday.getEightChar()
    logger.info(
        f"\nBaZi: {bazi.getYear()}, {bazi.getMonth()}, {bazi.getDay()}, {bazi.getTime()}"
    )

    # Get Wu Xing in LLM-ready JSON format
    # result = get_da_yun_wu_xing_interactive("戊", "子", lunar_birthday)
    assessor = WuXingAssessor(lunar_birthday)
    result = assessor.analyze()  # Analyze natal chart first
    # assessor.add_cycle_pillar("甲", "子", "da_yun")

    logger.info(f"\n--- JSON Output for LLM ---")
    logger.info(json.dumps(result, ensure_ascii=False, indent=2))